apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapps-project
spec:
  selector:
    matchLabels:
      app: webapps-project
  replicas: 2
  template:
    metadata:
      labels:
        app: webapps-project
    spec:
      containers:
      - name: webapps-project
        image: jebro/webapps:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
