apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapps-project-deployment
  labels:
    role: webapps
spec:
  selector:
    matchLabels:
      role: webapps
  replicas: 2

  template:
    metadata:
      labels:
        role: webapps

    spec:
      containers:
      - name: webapps
        image: jebro/webapps:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
