apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapps-project
spec:
  selector:
    matchLabels:
      app: webapps
  replicas: 2

  template:
    metadata:
      labels:
        app: webapps

    spec:
      containers:
      - name: webapps
        image: jebro/webapps
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
