apiVersion: v1
kind: Service
metadata:
  name: sampe-webapps-service
  labels:
    app: sample-webapps-project
spec:
  selector:
    app: sample-webapps-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort:8080
      nodePort: 8888    
