apiVersion: v1
kind: Service
metadata:
  name: webapps-service
  labels:
    app: webapps-project
spec:
  selector:
    app: webapps-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31202
